### ISSUE TITLE
Location detail popup has leading zeroes for months, but not days

### ISSUE THREAD

**Issue by bentorkington** [Questionable-Research-Labs/Govhack-2021#1]
Dates are displayed in ISO-8601 order (😎) but aren't quite compliant with the style. Leading zeroes should be used for all date components when displaying dates in this manner.

**Comment by Fallstop** [comment]
Hey there,
Thanks for leaving a issue, although they all somehow got completely missed till now. Your pull request can't be merged now, but I've quickly fixed it in commit 3aad42adcf0ca81b5b6e80384375364717e7a493
